# Generated by Django 3.1.7 on 2021-03-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_location_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='swipes',
            field=models.TextField(default=0, verbose_name='Свайпы'),
            preserve_default=False,
        ),
    ]
