# Generated by Django 3.1.7 on 2021-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subscription_swipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='swipes',
            field=models.TextField(default='', null=True, verbose_name='Свайпы'),
        ),
    ]
