# Generated by Django 3.1.7 on 2021-03-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210331_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='swipes_count',
            field=models.IntegerField(default=20, verbose_name='Кол-во свайпов'),
            preserve_default=False,
        ),
    ]
